#!/usr/bin/python
import sys
import re
lines = sys.stdin.readlines()
l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
l6 = []
l7 = []
l8 = []
l9 = []
l10 = []
l11 = []
l12 = []
l13 = []
l14 = []
l15 = []
l16 = []
l17 = []
lemma = sys.argv[1]
for line in lines:
    num = line.split(':')[0]
    if "!PubParams" in line:
        l1.append(num)
    elif "!KU( ~ltkCA" in line:
        l2.append(num)
    elif "!KU( ~ltkD" in line:
        l3.append(num)
    elif "F_Compromised_CAs" in line:
        l4.append(num)
    elif "!KU( sign(<'DomainCert'" in line:
        l5.append(num)
    elif "F_Sigs_Check_List" in line:
        l6.append(num)
    else:
        l7.append(num)
ranked = l1 + l2 + l3 + l4 + l5 + l6 + l7
for i in ranked:
    print i
