#!/usr/bin/python
import sys
import re
lines = sys.stdin.readlines()
l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
l6 = []
l7 = []
l8 = []
l9 = []
l10 = []
l11 = []
l12 = []
l13 = []
l14 = []
l15 = []
l16 = []
l17 = []
lemma = sys.argv[1]
for line in lines:
    num = line.split(':')[0]
    if "!PubParams" in line:
        l1.append(num)
    elif "!KU( ~Ltk" in line:
        l2.append(num)
    elif re.search("!KU.+sign.+DomainCert", line):
        l3.append(num)
    elif "!KU(" in line:
        l4.append(num)
    elif "L_Sigs_Revoke_Check_List" in line:
        l5.append(num)
    elif re.search("!KU.+sign.+RevokeCert", line):
        l6.append(num)
    elif re.search("In_S.+RevokeCert", line):
        l7.append(num)
    elif "!Sigs_Revoke_List_Final" in line:
        l8.append(num)
    elif "Sigs_Revoke_List" in line:
        l9.append(num)
    elif "F_BLM_Log(" in line:
        l10.append(num)
    elif "Sigs_List(" in line:
        l11.append(num)
    elif re.search("In_S.+RequestCert", line):
        l12.append(num)
    elif "L_Sigs_Check_List(" in line:
        l13.append(num)
    elif "!KU( pk(~" in line:
        l14.append(num)
    elif re.search("L_Blog.+blogid.+, blog", line):
        l15.append(num)
    else:
        l16.append(num)
ranked = l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8 + l9 + l10 + l11 + l12 + l13 + l14 + l15 + l16
for i in ranked:
    print i
